'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const dashboard = fs.readFileSync('spotify/dashboard.js', 'utf8');
const coverage = fs.readFileSync('spotify/coverage.js', 'utf8');
const index = fs.readFileSync('spotify/index.html', 'utf8');
assert.match(dashboard, /const BROWSE = window\.SPOTIFY_BROWSE_CATALOGUE \|\| \{\};/);
assert.match(dashboard, /const DISCOVERY_CATALOGUE = BROWSE_DISCOVERY/);
assert.match(dashboard, /function mergeFullDiscoveryCatalogue\(/);
assert.match(dashboard, /mergeFullDiscoveryCatalogue\(\);/);
assert.match(dashboard, /const LEGACY_R = \(D\.rows \|\| \[\]\)\.filter/);
assert.match(dashboard, /Tout le catalogue/);
assert.match(dashboard, /À mesurer/);
assert.match(dashboard, /Présentes en playlist éditoriale/);
assert.match(dashboard, /function arEditorialPlaylistEvidenceHtml\(/);
assert.match(dashboard, /Pourquoi cette musique est dans la liste/);
assert.match(dashboard, /Présence en playlists éditoriales/);
assert.match(dashboard, /function spotifyTrackEmbedHtml\(/);
assert.match(dashboard, /spotifyTrackEmbedHtml\(r\[6\],r\[1\],'track-modal-player'\)/);
assert.match(dashboard, /function trackEditorialEvidenceHtml\(/);
assert.match(dashboard, /trackEditorialEvidenceHtml\(r\)/);
const radarStart = dashboard.indexOf('function renderRadar(){');
const radarEnd = dashboard.indexOf('function renderWatch(){', radarStart);
assert.ok(radarStart >= 0 && radarEnd > radarStart, 'A&R render section must exist');
assert.doesNotMatch(dashboard.slice(radarStart, radarEnd), /id="radar-q"/, 'A&R search bar stays removed');
assert.match(coverage, /Catalogue vivant/);
assert.match(coverage, /A&R reste strict/);
assert.match(index, /Spotify_Browse_Catalogue_data\.js\?payload=/);
assert.match(index, /discovery\.css\?v=20260722-unified-catalogue-v1/);
assert.match(index, /dashboard\.js\?v=20260723-ar-release-position-v1/);
assert.match(dashboard, /function artistTrackClassification\(g\)/);
assert.match(dashboard, /genreSource:'tracks_catalogue'/);
assert.match(index, /coverage\.js\?v=20260722-unified-catalogue-v1/);
console.log('spotify unified catalogue guardrails: OK');
