'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const dashboard = fs.readFileSync('spotify/dashboard.js', 'utf8');
const coverage = fs.readFileSync('spotify/coverage.js', 'utf8');
const index = fs.readFileSync('spotify/index.html', 'utf8');
assert.match(dashboard, /const BROWSE = window\.SPOTIFY_BROWSE_CATALOGUE \|\| \{\};/);
assert.match(dashboard, /const DISCOVERY_CATALOGUE = BROWSE_DISCOVERY/);
assert.match(dashboard, /function mergeFullDiscoveryCatalogue\(/);
assert.match(dashboard, /mergeFullDiscoveryCatalogue\(\);/);
assert.match(dashboard, /const LEGACY_R = \(D\.rows \|\| \[\]\)\.filter/);
assert.match(dashboard, /Tout le catalogue/);
assert.match(dashboard, /Self-release/);
assert.match(dashboard, /Autre label/);
assert.match(dashboard, /function arEditorialPlaylistEvidenceHtml\(/);
assert.match(dashboard, /function arOpportunityPlayerHtml\(/);
assert.doesNotMatch(dashboard.slice(dashboard.indexOf('function openArOpportunity'), dashboard.indexOf('function arColumnBarHtml')), /Pourquoi cette musique est dans la liste/);
assert.match(dashboard, /Présence en playlists éditoriales/);
assert.match(dashboard, /function spotifyTrackEmbedHtml\(/);
assert.match(dashboard, /function spotifyCenteredTrackPlayerHtml\(/);
assert.match(dashboard, /spotifyCenteredTrackPlayerHtml\(r\[6\],r\[1\]\)/);
assert.match(dashboard, /wrapper\._spotifyController\.togglePlay\(\)/);
assert.match(dashboard, /function openTrackFromCatalogueRow\(event,tid\)/);
assert.match(dashboard, /onclick="openTrackFromCatalogueRow\(event,'\$\{r\[6\]\}'\)"/);
assert.match(dashboard, /target\.closest\('a,button,input,select,option,label,\.ar,\.tk,\[data-no-track-open\]'\)/);
assert.match(dashboard, /function trackEditorialEvidenceHtml\(/);
assert.match(dashboard, /trackEditorialEvidenceHtml\(r\)/);
assert.match(dashboard, /function arEditorialPlaylistPanelHtml\(/);
assert.match(dashboard, /return arEditorialPlaylistPanelHtml\(opportunity,'Présence en playlists éditoriales'\)/);
assert.match(dashboard, /function arEditorialPlaylistCoverHtml\(/);
assert.match(dashboard, /hydrateArPlaylistCovers\(\);/);
const radarStart = dashboard.indexOf('function renderRadar(){');
const radarEnd = dashboard.indexOf('function renderWatch(){', radarStart);
assert.ok(radarStart >= 0 && radarEnd > radarStart, 'A&R render section must exist');
assert.match(dashboard.slice(radarStart, radarEnd), /id="radar-q"/, 'A&R search bar is available beside the genre filter');
assert.match(coverage, /Catalogue vivant/);
assert.match(coverage, /A&R reste strict/);
assert.match(index, /Spotify_Browse_Catalogue_data\.js\?payload=/);
assert.match(index, /discovery\.css\?v=20260722-unified-catalogue-v1/);
assert.match(index, /dashboard\.js\?v=20260724-spotify-rate-limit-fix-v1/);
assert.match(dashboard, /const SPOTIFY_WEB_LOCALE='en'/);
assert.match(dashboard, /locale=\$\{SPOTIFY_WEB_LOCALE\}/);
assert.match(dashboard, /function artistTrackClassification\(g\)/);
assert.match(dashboard, /genreSource:'tracks_catalogue'/);
assert.match(index, /coverage\.js\?v=20260723-stale-copy-cleanup-v1/);
console.log('spotify unified catalogue guardrails: OK');
